### ISSUE TITLE
Make website more compatible with mobile devices

### ISSUE THREAD

**Issue by jac803** [ReTtiChDieOrganisation/ReTtiChDasRepo#109]
**Is your enhancement related to a problem? Please describe.**
Currently the website is really bad for mobile devices.

**Describe the solution you'd like**
I would the website to be more compatible with mobile devices.

**Add Todos**
- [ ] Redesign and reorder index.html
- [ ] Create style.css as seperate file
- [ ] Create seperate javascript file for the interactive part

**Comment by FelixTe** [comment]
Die übrigen Todos hören sich auch sehr nah an #50 an wo @prosauer schon ein WIP pull request gemacht (https://github.com/ReTtiChDieOrganisation/ReTtiChDasRepo/pull/108)  hat. Weil wir die Schulung noch nicht hatten weiß halt kein Mensch was das sein soll.
Vielleicht das was du jetzt hast in den main mergen und für dieses redesign and reorder und create seperate files ein eigenes Issue aufmachen und dann mit @prosauer und issue #50 die todos zusammenführen?

**Comment by jac803** [comment]
Oh habe ich grade erst gesehen... Ich fürchte, dass die Änderungen bei mir etwas ausgeartet sind :D Hatte die javascript und css Sachen jetzt auch schon in eigene Dateien ausgegliedert. Aber vielleicht bekomme ich die Sachen ja auch mit den Änderungen von @prosauer händisch gemerged. Ist der pull request (#108) denn jetzt schon so weit, dass der in den main gemerged werden kann? Ich kann mir heute Abend die Änderungen da mal angucken.

**Comment by FelixTe** [comment]
Irgendwie ist das ein draft ich weiß nicht was das bedeutet aber der will gar nicht gemerged werden

**Comment by FelixTe** [comment]
Aber ich denke wenn ihr jetzt was ähnliches gemacht habt können wir einfach eine Sache nehmen
