### ISSUE TITLE
Restart takes very long when displaying many riders

### ISSUE THREAD

**Issue by jac803** [ReTtiChDieOrganisation/ReTtiChDasRepo#116]
**Describe the bug**
When trying to restart the map, while e. g. all riders are selected, the process takes a very long time. The behavior is independant from the device. Testet on Desktop and Mobile Device.

**To Reproduce**
1. Open page
2. Click on 'Restart'
3. See behavior/error

**Expected behavior**
The process shouldn't take that long.

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome
 - 118.0.5993.118

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 16.3
 - Browser stock browser

**Additional context**
Fix is integreated into issue #115

**Comment by FelixTe** [comment]
Wie hast du das gefixt @jac803?

**Comment by jac803** [comment]
Kann man hier Code markieren und verlinken? @FelixTe

**Comment by FelixTe** [comment]
Keine Ahnung

**Comment by jac803** [comment]
Es wurde auf jeden Fall doppelt iteriert. Deshalb hat das so lange gedauert...
