### ISSUE TITLE
Does not reset when choosing different segment

### ISSUE THREAD

**Issue by FelixTe** [ReTtiChDieOrganisation/ReTtiChDasRepo#117]
Wenn man ein segment auswählt und dann die geschwindigkeit hoch stellt und dann ein neues segment einstellt dann wird die geschwindigkeit zwar zurück gesetzt aber die angezeige "x N" nicht. Und auch die start und end punkte des segments werden nicht gelöscht

**Comment by FelixTe** [comment]
Ich versuche das mal zu fixen

**Comment by jac803** [comment]
Ok, ansonsten weiß ich glaube ich woran es liegt. @FelixTe
