### ISSUE TITLE
Datenladen unabhängig von Anzahl Leute machen

### ISSUE THREAD

**Issue by FelixTe** [ReTtiChDieOrganisation/ReTtiChDasRepo#29]
Keine Hardcoded namen mehr alles nur noch in unique identifier

**Comment by Flo1314** [comment]
Aber ne hardcoded Reihenfolge von uns (Philipp, Felix, flo) bleibt aktuell noch. Da könnte man sich auch noch was überlegen zB wegen den Farben.

**Comment by Flo1314** [comment]
Klassiker: hardcoded oder hardcodet?
