### ISSUE TITLE
Create Icon for new members

### ISSUE THREAD

**Issue by FelixTe** [ReTtiChDieOrganisation/ReTtiChDasRepo#40]
An die neuen subscriber schickt dem Flo ein Bild oder lasst euch von Flo erklären wie man mit Hilfe der Powerpoint Vorlage ein Icon erstellt

**Comment by herrdavidera** [comment]
@Flo1314 erklär es uns

**Comment by FelixTe** [comment]
Vielleicht könnte der Workflow auch bisschen automatisiert werden. Wir erwarten ja einen riesen Ansturm

**Comment by Flo1314** [comment]
@herrdavidera, @Luisa-W, nehmt die powerpointvorlage in frontend/piqs und setzt euer Bild da rein, wie es euch gut gefällt. Ändert die Farbe zu der, die ihr wollt (super wäre es wenn ihr mir die gewählte Farbe dann als rgb Wertepaar schicken könnt, das sieht man in powerpoint dann in der Farbpalette wenn man die auswählt).

Anschließend einfach als grafik (png) Speichern. Ich hab die png dann in Gimp noch auf 100 pixel breite skaliert. Einfach die png in Gimp öffnen und dann Bild>skalieren.

Zum Schluss das Bild einfach in den etc/piqs Ordner legen und pushen.

PS: beim schreiben fällt mir auf wie nervig der workflow ist haha

**Comment by Flo1314** [comment]
der wirkliche pain beim automatisieren ist die Farbauswahl. Aber wäre sehr schön das zu machen und dann auch automatisch für die polyline einzustellen.

Aktuell muss es so sein, aber dafür bekommt man es in powerpoint so hin dass es ganz nett aussieht

**Comment by herrdavidera** [comment]
@Flo1314 ist das immernoch aktuell dass ich die Powerpoint vorlage nehmen soll oder leg ich ein bild in der richtigen größe in etc/piqs ab?

**Comment by FelixTe** [comment]
gut dass du Beispielpixel für 3:4 angegeben hast👍

**Comment by Flo1314** [comment]
ja ich weiß nicht was 3:4 und was 4:3 ist und ich wollte vermeiden dass David sich in 8k hochlädt

**Comment by Flo1314** [comment]
Ne Fahrräder

**Comment by FelixTe** [comment]
Ich glaube @Luisa-W es wäre gut wenn du das auch nochmal so machst oder @Flo1314 ?

**Comment by Luisa-W** [comment]
werde es zu meiner extrem langen to do Liste für dieses Projekt hinzufügen

**Comment by FelixTe** [comment]
Spätestens wenn die neue Website hochgeladen wird und du immer als default Bild angezeigt wirst wird das sehr schnell gehen da bin ich sicher
