### ISSUE TITLE
Treat entire ride as a segment

### ISSUE THREAD

**Issue by prosauer** [ReTtiChDieOrganisation/ReTtiChDasRepo#44]
With that we don't need alle the if()else() calls to check if no segment is choosen

**Comment by FelixTe** [comment]
Aber die haben ja dann keinen gemeinsamen Start und endpunkt. Um welche if else geht es denn vielleicht kann man da anders elegant mit umgehen.

**Comment by FelixTe** [comment]
Ah man könnte natürlich da wo jetzt steht choose segment sowas hin schreiben wie "full ride" und dann muss man nur noch einmal in der draw segment funktion abfangen, dass wenn full ride ausgewählt wird die start und endpunkte einfach als indices übergeben werden

**Comment by prosauer** [comment]
Wir fragen doch eh für jeden rider die start und end indizes ab für die segmente. Also das ist zwar totaler Quatsch, weil die ja gleich sein *sollten*, aber machen wir ja trotzdem. Und könnte hier eigentlich praktisch sein, weil der "full ride" dann einfach unterschiedliche start und end indizes haben kann, aber halt trotzdem im segments array drin ist

**Comment by prosauer** [comment]
`start_idx_set = [segments[seg_name].Philipp.start_index,segments[seg_name].Felix.start_index,segments[seg_name].Flo.start_index]
				end_idx_set = [segments[seg_name].Philipp.end_index,segments[seg_name].Felix.end_index,segments[seg_name].Flo.end_index]`
