### ISSUE TITLE
Mega cooles refactoring hört dafür die zweite Sprachnachricht

### ISSUE THREAD

**Issue by FelixTe** [ReTtiChDieOrganisation/ReTtiChDasRepo#45]
- [x] über die medals auf der rechten Seite ein drop-down Menü wo man die Gruppen auswählen kann
- [x] Untitled0 so umstellen dass die datenstruktur (s.u.) erzeugt wird 
- [x] index.html umstellen dass die Datenstruktur (s.u) unten genutzt werden kann
- [x] define groups (siehe Kommentar)

Datenstruktur:
- Eine File mit allen touren wie jetzt z.b. felix_json zu den jetztigen daten muss noch ein Feld mit dem unqiue identifier für die:den Fahrer:in und eine id für die Tour (vielleicht einfach strava id nehmen)
- Eine File mit Groups darin für jede Gruppe die dazugehörigen ids der Fahrten die namen und die medals und stats

**Comment by FelixTe** [comment]
Und dann kann man gruppen angeben und das sind dann einfach subsets der fahrten

**Comment by FelixTe** [comment]
Wir müssen uns überlegen wie wir eine Gruppe definieren.
Wenn Philipp Flo ich zum DLR fahren finde ich sollte das eine Gruppe sein. Eine weitere Möglichkeit wäre, dass das die Gruppen (P, Fe), (Fe,FL) (FL, P) und (Fl, Fe, P) und das wäre zu cluttering

Also ich würde sagen eine Gruppe sind Fahrten die mindestens N(z.b. 10) Segmente Teilen und innerhalb von 18h gestartet sind(damit wir nicht Fahrten von zwei Tagen drin haben) aber dann muss man sich noch überlegen wie man die Untergruppen ausschließt. Vielleicht immer die größte Gruppe einfach nehmen

**Comment by Flo1314** [comment]
Gruppen selber definieren können durch Viereck ziehen: man zieht ein Start Viereck mit Maustaste gedrückt halten auf der map und danach zieht man ein end Viereck. Alle teilnehmende die in den letzten 24h eine Fahrt gemacht haben die innerhalb des ersten Vierecks startet und im zweiten aufhört werden zu einer Gruppe zusammen getan

**Comment by FelixTe** [comment]
Ja erstmal glaube ich reicht so ein dropdown weil so viele werden dass ja nicht sein. Und wenn man nicht zur arbeit fährt oder irgendwo hin fährt ist das schwer. Angenommen wir wissen, dass david, philipp und ich irgendwo in Hürth zusammen gefahren sind dann ist start und end viereck komplett köln linksrheinisch

**Comment by FelixTe** [comment]
TODO:
- draw segments
- table füllen automatisch
- medal figure automatic with no riders
- bug fixen dass segmente nur nach dem ersten auswählen der gruppe aktualisiert werden
