### ISSUE TITLE
Maybe last week instead of last 24h

### ISSUE THREAD

**Issue by FelixTe** [ReTtiChDieOrganisation/ReTtiChDasRepo#49]
Follow up zu #45 

Wenn man die letzte Woche hat, hat man ein bisschen mehr zum angucken. Dann benötigt man wahrscheinlich auch irgendwelche buttons um den Tag einzustellen. Und wahrscheinlich sollte man dann auch die daten lokal (nicht auf git!) speichern in einem "raw_data" ordner, damit man immer abgleichen kann welche schon da sind und die nicht nochmal laden muss. Wegen performance und wegen begrenzter anzahl an api requests

**Comment by prosauer** [comment]
boah, so langsam müsste man sich da mal richtige Datenbank-Gedanken machen. Finde ich persönlich immer sehr anstrengend

**Comment by prosauer** [comment]
Das mit dem issues richtig verlinken, sodass sie automatisch geschlossen werden, müssen wir uns in github auch mal anschauen, in gitlab ist das bisschen more straightforward....
