### ISSUE TITLE
riders profile pictures independent of icon frames

### ISSUE THREAD

**Issue by Flo1314** [ReTtiChDieOrganisation/ReTtiChDasRepo#59]

**Comment by FelixTe** [comment]
Check ich nicht

**Comment by Flo1314** [comment]
icon = profilbild + frame

profilbild:
![image](https://github.com/ReTtiChDieOrganisation/ReTtiChDasRepo/assets/64836791/45ed11c8-1c59-44c9-a667-169114966bbe)

frame:
![bg_pride](https://github.com/ReTtiChDieOrganisation/ReTtiChDasRepo/assets/64836791/3213d106-86f6-442f-ac60-e1b499eb256b)

Damit die frames gewechselt werden können. zB bei segment auswahl bekommt der erste nen goldenen frame usw.

**Comment by Flo1314** [comment]
rider.name("Felix").set_frame("green") soll dein frame dann auf das grüne:
![fg_green](https://github.com/ReTtiChDieOrganisation/ReTtiChDasRepo/assets/64836791/096da4ed-f3eb-49f0-8727-f71f8e00962b)
setzen. Das ist die idee. 
Gleiches dann mit der polyline color: rider.name("Felix").set_polyline_color("green") bspw
