### ISSUE TITLE
Change RGB Values of frames arbitrarily

### ISSUE THREAD

**Issue by FelixTe** [ReTtiChDieOrganisation/ReTtiChDasRepo#62]
Also so dass es wie in #59 schon auch vorgefertigte frames gibt aber man auch rinder.setframe([23,29,80]) und dann den frame zu dem RGB wert 23,29,80

Man muss sich dann überlegen wie man es schafft dass das da außen drum herum bisschen dunkler wird aber vielleicht gibt es ja eine Art wie man die gleiche Farbe in dunkler bekommt

**Comment by FelixTe** [comment]
Vielleicht kann man auch einfach eine Weiß graue Vorlage machen für das Dreieck unten und den Rand und dann irgendwie Farbe adden und dann wird das automatisch diese heller dunkler Abstufung

**Comment by prosauer** [comment]
Welche Rinder bekommen einen frame und was passiert damit? Bitte um Aufklärung @FelixTe

**Comment by prosauer** [comment]
Und dann bitte labeln :)

**Comment by FelixTe** [comment]
Hat sich glaube ich erledigt 🐄
