### ISSUE TITLE
Should we split up groups?

### ISSUE THREAD

**Issue by FelixTe** [ReTtiChDieOrganisation/ReTtiChDasRepo#81]
If riders a, b, c have 10 segments in common and a,b have 15 should we get groups (abc) and (ab) or is it sufficient to have abc

**Comment by prosauer** [comment]
I think there should be a reasonable threshold. In case of 5 extra segments, yes we should split groups. But not if only 1 is missing, probably.

**Comment by FelixTe** [comment]
Maybe even 10. Von der Drehbrücke zur Rodenkirchener sind schon 10 Segmente das geht schnell. Also kann man da ein neues Feature request zu aufmachen mmn

**Comment by Flo1314** [comment]
Nicht sicher ob das noch zu weit entfernt ist aber zusätzlich gut wäre doch eigentlich eine Suchleiste wo ich dann rider zu meiner Gruppe Adden kann, oder?

Bspw fange ich mit Felix an und danach suche ich nach Philipp. Wenn ich die beiden in der Gruppe hab kriege ich gesagt dass Felix und Philipp in den letzten 7 Tagen 3 gemeinsame rides (im Sinne von mindestens ein gemeinsames Segment) hatten und ich kann auswählen welche davon ich mir anschauen möchte. 

Da sind wir dann nur bisschen wieder in dem Problem dass das sehr rider anstatt ride bezogen ist, meine Idee finde ich trotzdem toll

**Comment by FelixTe** [comment]
Ich denke bei Gruppen macht eher Sinn nach Rides zu gehen als mach Rider. Wenn ich zum Beispiel eine Fahrt mit @herrdavidera mache (ich weiß unrealistisch weil der so wenig fährt) und dann mit euch @Flo1314 @prosauer zur Arbeit fahre sollte mein Ride mit David in einer Gruppe sein mit David s fahrt und meine Fahrt zur Arbeit in einer Gruppe mit euren fahrten

**Comment by Flo1314** [comment]
Ja, meine Überlöegung geht ja dahin dass man kein dropdown mit 200 möglichen Gruppen hat, sondern man sich diese selber per klicken zusammenstellt. 

Stell dir vor du suchst dort nach Felix und dann kriegst du deine 3 Fahrten der letzten Woche vorgeschlagen. Während du darüber hoverst werden die polylines auf der map angezeigt damit du die ganze Fahrt siehst. Dann wählst du eine Fahrt aus. Dann suchst du nach einer Weiteren Person und es werden alle Fahrten dieser Person vorgeschlagen die sich mindestens ein Segment mit deiner Fahrt teilen. Beim drüber hovern werden wieder die poyllines angezeigt und sich überschneidende segmente könnten jetzt sogar rot hinterlegt werden oder so. Und so stellst du dir gruppen zusammen.

**Comment by Flo1314** [comment]
Und natürlich kannst du dabei auch deine Fahrt A mit deiner Fahrt B in eine Gruppe tun.

**Comment by FelixTe** [comment]
Haha ja das hört sich gut an

**Comment by FelixTe** [comment]
Aber da brauchen wir ne andere Datenbank Infrastruktur

**Comment by Flo1314** [comment]
Vielleicht sollten wir eh auf ne dynamische Datenbank anstatt auf json files setzen. Wenn das alles so einfach und schnell ginge

**Comment by FelixTe** [comment]
Dann musst du auch nicht mehr dich damit auseinandersetzen wie man jsons lädt
