### ISSUE TITLE
Why are there some rides from flo with power data?

### ISSUE THREAD

**Issue by FelixTe** [ReTtiChDieOrganisation/ReTtiChDasRepo#83]
Z.b. fahrt an 2023-10-16T15:28:46Z

**Comment by FelixTe** [comment]
Kann es sein dass sich der Wahoo noch mit deinem Powermeter verbindet @prosauer

**Comment by Flo1314** [comment]
haha

**Comment by FelixTe** [comment]
Es ist nämlich nur bei rückwegen wo ihr zusammen gestartet seid
